/**
 * Arabic Language Translations
 * Edit this file to update Arabic text across the website.
 * Keys must match those in script.js (en/ar objects).
 */
window.TRANSLATIONS_AR = {
    'nav.brand': 'ركوب الدراجات في كل مكان',
    'nav.home': 'الرئيسية',
    'nav.about': 'من نحن',
    'nav.language': 'اللغة',
    'nav.theme': 'المظهر',
    'hero.b1': '✓ انضم إلى رحلات دراجات منظمة',
    'hero.b2': '✓ قد في الطبيعة والمدينة والجبال وفي كل مكان بأمان',
    'hero.b3': '✓ تعرّف على أشخاص يشاركونك الشغف',
    'hero.b4': '✓ جميع المستويات مرحب بها',
    'hero.b5': '✓ مرشدون محليون ومجتمع داعم',
    'trust.verified': 'مرشدون معتمدون',
    'trust.vehicle': 'مركبة دعم مرافقة',
    'trust.rentals': 'دراجات للإيجار متاحة',
    'about.title': 'من نحن',
    'about.text': 'نحن منظمة ركوب دراجات هدفنا التعارف والاستمتاع واكتشاف العالم والرياضة والصحة.',
    'about.card1.title': 'التواصل الاجتماعي',
    'about.card1.text': 'ابنِ علاقات ذات معنى مع عشاق الدراجات واصنع صداقات دائمة على الطريق.',
    'about.card2.title': 'استكشاف العالم',
    'about.card2.text': 'اكتشف وجهات جديدة، من المناظر الحضرية إلى عجائب الطبيعة، بركوب آمن مع مرشدين خبراء.',
    'about.card3.title': 'الصحة والعافية',
    'about.card3.text': 'حسّن لياقتك البدنية وصحتك النفسية من خلال مغامرات الدراجات المنتظمة في أجواء جميلة.',
    'gallery.title': 'التجربة',
    'gallery.friendship': 'المرح والصداقة',
    'gallery.views': 'مناظر خلابة',
    'gallery.quality': 'دراجات عالية الجودة',
    'gallery.refresh': 'استراحة وانتعاش',
    'prep.title': 'ماذا تحضر معك',
    'prep.water': 'ماء',
    'prep.helmet': 'خوذة (سلامة)',
    'prep.tube': 'أنبوب داخلي احتياطي',
    'prep.clothes': 'ملابس مريحة',
    'prep.alt.water': 'زجاجة ماء',
    'prep.alt.helmet': 'خوذة دراجة',
    'prep.alt.tube': 'أنبوب داخلي احتياطي',
    'footer.copy': '© 2026 ركوب الدراجات في كل مكان. جميع الحقوق محفوظة.',
    'note.privacy': 'معلوماتك محفوظة بسرية ولن تُستخدم إلا لتنظيم وإدارة هذا الحدث.',
    'cta.indexTitle': 'جاهز للانضمام للرحلة؟',
    'cta.indexButton': 'الانتقال إلى صفحة المعلومات',
    'cta2.title': 'جاهز للانضمام للرحلة؟',
    'cta2.text': 'انتقل إلى مركز المعلومات لتأكيد التفاصيل والتسجيل.',
    'cta2.btn': 'الانتقال إلى صفحة المعلومات',
    'hub.hero.tag': 'أم قيس · إربد',
    'hub.hero.title': 'رحلة شروق الشمس في أم قيس',
    'hub.hero.desc': 'انضم إلى رحلة شروق الشمس الموجهة في أم قيس بعد السبوعين الجمعة. انطلق في الساعة 8:00 صباحاً واستمتع بـ ~4 ساعات من ركوب الدراجات الخلابة.',
    'hub.facts.city': 'إربد، الأردن',
    'hub.facts.time': '8:00 صباحاً',
    'hub.facts.duration': '~4 ساعات',
    'hub.who.title': 'لمن هذه الرحلة',
    'hub.who.text': 'جميع المستويات مرحب بها. سيكون لدينا قادة دراجات للمبتدئين ومجموعات أسرع للمحترفين—حتى تركب بالسرعة التي تناسبك.',
    'hub.highlights.title': 'أبرز التجربة',
    'hub.highlights.item1': 'مناظر خلابة بحيرة طبريا',
    'hub.highlights.item2': 'آثار رومانية تاريخية',
    'hub.highlights.item3': 'إفطار طازج في الطبيعة',
    'hub.highlights.item4': 'أجواء مجتمعية رائعة',
    'hub.bring.title': 'ماذا تحضر معك',
    'hub.bring.water': 'ماء — 1.5 لتر',
    'hub.bring.helmet': 'خوذة — إلزامية',
    'hub.bring.id': 'بطاقة هوية — احملها',
    'hub.bring.sun': 'واقي شمس — يُنصح بـ +SPF 50',
    'hub.safety.title': 'السلامة',
    'hub.safety.item1': 'مرشدون معتمدون',
    'hub.safety.item2': 'إسعافات أولية في الموقع',
    'hub.safety.item3': 'مركبة دعم تتبع المجموعة',
    'hub.faq.title': 'الأسئلة الشائعة',
    'hub.faq.q1': 'هل يتم توفير المواصلات؟',
    'hub.faq.a1': 'يرجى ترتيب مواصلاتك إلى أم قيس. سنشارك نقطة اللقاء بعد التسجيل.',
    'hub.faq.q2': 'ماذا لو كان هناك مطر؟',
    'hub.faq.a2': 'نقود إذا كانت الظروف آمنة، وإلا سنخبرك بخطة محدثة.',
    'hub.faq.q3': 'هل الطريق مرتفع؟',
    'hub.faq.a3': 'نعم، لكن لدينا دعم! قادة سرعة، محطات راحة، ومركبة متابعة تغطيك.',
    'hub.bike.title': 'لا تملك دراجة؟ لا مشكلة!',
    'hub.bike.text': 'يمكنك طلب استئجار دراجة أثناء ملء نموذج التسجيل.',
    'hub.bike.btn': 'التسجيل و/أو استئجار دراجة',
    'hub.cta.button': 'التسجيل و/أو استئجار دراجة',
    'reg.tag': 'Cycling Every Where',
    'reg.title': 'انضم إلى مغامرة ركوب الدراجات',
    'reg.subtitle': 'املأ النموذج أدناه للتسجيل في رحلتنا القادمة',
    'reg.personal': 'المعلومات الشخصية',
    'reg.fullname': 'الاسم الكامل',
    'reg.email': 'البريد الإلكتروني',
    'reg.phone': 'رقم الهاتف',
    'reg.rental': 'استئجار دراجة',
    'reg.needBike': 'هل تحتاج إلى استئجار دراجة؟',
    'reg.yes': 'نعم',
    'reg.no': 'لا',
    'reg.bikeType': 'نوع الدراجة المفضل',
    'reg.selectBikeType': 'اختر نوع الدراجة',
    'reg.bikeType.mountain': 'دراجة جبلية',
    'reg.bikeType.road': 'دراجة طريق',
    'reg.bikeType.hybrid': 'دراجة هجينة',
    'reg.bikeType.electric': 'دراجة كهربائية',
    'reg.riderHeight': 'طول الراكب (للمقاس)',
    'reg.selectHeight': 'اختر الطول',
    'reg.additional': 'معلومات إضافية',
    'reg.experienceLevel': 'مستوى الخبرة',
    'reg.selectExperience': 'اختر مستوى الخبرة',
    'reg.level.beginner': 'مبتدئ',
    'reg.level.intermediate': 'متوسط',
    'reg.level.advanced': 'متقدم',
    'reg.emergency': 'اسم ورقم التواصل للطوارئ',
    'reg.notes': 'ملاحظات أو طلبات خاصة',
    'reg.submit': 'إتمام التسجيل',
    'reg.help': 'تحتاج مساعدة؟ اتصل بنا على',
    'reg.thankYouTitle': 'شكراً لتسجيلك! يسعدنا انضمامك إلى مغامرة ركوب الدراجات.',
    'reg.thankYouFollowUp': 'سيتواصل معك فريقنا قريباً لتأكيد مكانك.',
    'note.privacyReg': 'معلوماتك محفوظة بسرية ولن تُستخدم إلا لتنظيم وإدارة هذا الحدث.',
    'confirm.title': 'تم تأكيد التسجيل!',
    'confirm.subtitle': 'شكراً لتسجيلك مع Cycling Every Where. يسعدنا انضمامك إلى مغامرتنا القادمة!',
    'confirm.next': 'ما الخطوة التالية؟',
    'confirm.step1': 'ستصلك رسالة تأكيد بجميع التفاصيل خلال 24 ساعة.',
    'confirm.step2': 'سنتواصل لتأكيد موعد الرحلة ومكان التجمع.',
    'confirm.step3': 'إن طلبت دراجة للإيجار، سنؤكد التوفر والمقاس.',
    'confirm.backHome': 'العودة إلى الرئيسية',
    'confirm.contact': 'تواصل معنا',
    'confirm.home': 'الرئيسية',
    'confirm.viewPage': 'عرض صفحة التأكيد',
    'cta.proceedReg': 'المتابعة للتسجيل',
    'reg.placeholder.name': 'أدخل اسمك الكامل (مقطعين على الأقل)',
    'reg.placeholder.email': 'بريدك@example.com',
    'reg.placeholder.phone': '00962781234567',
    'reg.placeholder.phoneSuffix': '781234567',
    'reg.placeholder.emergency': 'الاسم ورقم الهاتف',
    'reg.placeholder.notes': 'أي متطلبات خاصة أو أسئلة...',
    'reg.height.140': '140-150 سم',
    'reg.height.150': '150-160 سم',
    'reg.height.160': '160-170 سم',
    'reg.height.170': '170-180 سم',
    'reg.height.180': '180-190 سم',
    'reg.height.190': '190+ سم',
    'lightbox.close': 'إغلاق',
    'whatsapp.tooltip': 'تواصل معنا',
    'whatsapp.aria': 'الدردشة على واتساب'
};
